// docs/.vitepress/theme/components/Permissions.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useData } from 'vitepress'
import { pickStrings } from '../data/infographics'

const { lang } = useData()
const t = computed(() => pickStrings(lang.value).perms)

const rwx = ['r', 'w', 'x']
const weights = [4, 2, 1]
const groups = computed(() => [
  { key: 'owner', label: t.value.owner, bits: [true, true, true] },   // rwx = 7
  { key: 'group', label: t.value.group, bits: [true, false, true] },  // r-x = 5
  { key: 'other', label: t.value.other, bits: [true, false, true] },  // r-x = 5
])
const digit = (bits: boolean[]) => (bits[0] ? 4 : 0) + (bits[1] ? 2 : 0) + (bits[2] ? 1 : 0)
</script>

<template>
  <figure class="ig">
    <figcaption class="ig-title">
      {{ t.title }}
      <img class="ig-art" src="/images/info-lock.png" alt="" loading="lazy" />
    </figcaption>
    <div class="perm">
      <span class="seg t">-</span>
      <span class="seg g-owner">rwx</span>
      <span class="seg g-group">r-x</span>
      <span class="seg g-other">r-x</span>
      <span class="eq">= 755</span>
    </div>
    <div class="cards">
      <div v-for="g in groups" :key="g.key" class="card" :class="g.key">
        <div class="clabel">{{ g.label }}</div>
        <svg class="bits" viewBox="0 0 134 38" aria-hidden="true">
          <g v-for="(b, bi) in g.bits" :key="bi">
            <rect class="bit" :class="b ? 'on ' + g.key : 'off'" :x="bi * 44 + 2" y="2" width="40" height="34" rx="5" />
            <text class="bc" :class="{ off: !b }" :x="bi * 44 + 22" y="18" text-anchor="middle">{{ b ? rwx[bi] : '-' }}</text>
            <text class="bw" :class="{ off: !b }" :x="bi * 44 + 22" y="30" text-anchor="middle">{{ weights[bi] }}</text>
          </g>
        </svg>
        <div class="digit" :class="g.key">{{ digit(g.bits) }}</div>
      </div>
    </div>
    <div class="legend">
      <span><b>r</b> {{ t.r }} · 4</span>
      <span><b>w</b> {{ t.w }} · 2</span>
      <span><b>x</b> {{ t.x }} · 1</span>
    </div>
    <p class="ig-note">{{ t.note }}</p>
  </figure>
</template>

<style scoped>
.ig { border: 1px solid var(--vp-c-divider); border-radius: 12px; background: var(--vp-c-bg-soft); padding: 20px 22px; margin: 22px 0; }
.ig-title { font-weight: 600; font-size: 15px; color: var(--vp-c-text-1); margin-bottom: 14px; display: flex; align-items: center; justify-content: space-between; gap: 12px; }
.ig-art { width: 52px; height: 52px; flex: 0 0 auto; }
.perm { font-family: var(--vp-font-family-mono); font-size: 26px; letter-spacing: 2px; display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }
.perm .seg { padding: 2px 8px; border-radius: 6px; font-weight: 700; }
.perm .t { color: var(--vp-c-text-3); }
.perm .g-owner { background: var(--vp-c-red-soft); color: var(--vp-c-red-1); }
.perm .g-group { background: var(--vp-c-green-soft); color: var(--vp-c-green-1); }
.perm .g-other { background: var(--vp-c-indigo-soft); color: var(--vp-c-indigo-1); }
.perm .eq { font-size: 22px; color: var(--vp-c-text-2); margin-left: 4px; }
.cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-top: 16px; }
.card { border: 1px solid var(--vp-c-divider); border-radius: 9px; padding: 10px; text-align: center; background: var(--vp-c-bg); }
.clabel { font-size: 13px; font-weight: 600; color: var(--vp-c-text-1); margin-bottom: 6px; }
.bits { width: 100%; max-width: 134px; height: auto; }
.bit.off { fill: var(--vp-c-bg-alt); stroke: var(--vp-c-divider); }
.bit.on.owner { fill: var(--vp-c-red-soft); stroke: var(--vp-c-red-1); }
.bit.on.group { fill: var(--vp-c-green-soft); stroke: var(--vp-c-green-1); }
.bit.on.other { fill: var(--vp-c-indigo-soft); stroke: var(--vp-c-indigo-1); }
.bit { stroke-width: 1.4; }
.bc { fill: var(--vp-c-text-1); font-size: 13px; font-weight: 700; font-family: var(--vp-font-family-mono); }
.bw { fill: var(--vp-c-text-3); font-size: 9px; }
.bc.off, .bw.off { fill: var(--vp-c-text-3); }
.digit { font-size: 22px; font-weight: 700; margin-top: 4px; font-family: var(--vp-font-family-mono); }
.digit.owner { color: var(--vp-c-red-1); }
.digit.group { color: var(--vp-c-green-1); }
.digit.other { color: var(--vp-c-indigo-1); }
.legend { display: flex; gap: 18px; flex-wrap: wrap; margin-top: 14px; font-size: 13px; color: var(--vp-c-text-2); }
.legend b { font-family: var(--vp-font-family-mono); color: var(--vp-c-text-1); }
.ig-note { color: var(--vp-c-text-2); font-size: 13px; margin: 14px 0 0; line-height: 1.6; }
@media (max-width: 520px) { .cards { grid-template-columns: 1fr; } .perm { font-size: 22px; } }
</style>

// web/components/infographics/Permissions.tsx
'use client';
import { useI18n } from 'fumadocs-ui/contexts/i18n';
import { pickStrings } from '@/lib/infographics';
import { localeKey } from './shared';

const RWX = ['r', 'w', 'x'];
const WEIGHTS = [4, 2, 1];

function digit(bits: boolean[]) {
  return (bits[0] ? 4 : 0) + (bits[1] ? 2 : 0) + (bits[2] ? 1 : 0);
}

export function Permissions() {
  const { locale } = useI18n();
  const t = pickStrings(localeKey(locale)).perms;
  const groups = [
    { key: 'owner', label: t.owner, bits: [true, true, true], color: '#D70A53', soft: 'rgba(215,10,83,.12)' },
    { key: 'group', label: t.group, bits: [true, false, true], color: '#16a34a', soft: 'rgba(22,163,74,.12)' },
    { key: 'other', label: t.other, bits: [true, false, true], color: '#6366f1', soft: 'rgba(99,102,241,.12)' },
  ];
  return (
    <figure className="my-6 rounded-xl border bg-fd-card/40 p-5">
      <figcaption className="mb-4 flex items-center justify-between gap-3 text-sm font-semibold text-fd-foreground">
        <span>{t.title}</span>
        <img src="/images/info-lock.png" alt="" loading="lazy" className="h-12 w-12 shrink-0" />
      </figcaption>

      <div className="flex flex-wrap items-baseline gap-2 font-mono text-2xl font-bold tracking-widest">
        <span className="text-fd-muted-foreground">-</span>
        {groups.map((g) => (
          <span key={g.key} className="rounded-md px-2 py-0.5" style={{ background: g.soft, color: g.color }}>
            {g.bits.map((b, i) => (b ? RWX[i] : '-')).join('')}
          </span>
        ))}
        <span className="ml-1 text-xl text-fd-muted-foreground">= 755</span>
      </div>

      <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3">
        {groups.map((g) => (
          <div key={g.key} className="rounded-lg border bg-fd-background p-2.5 text-center">
            <div className="mb-1.5 text-[13px] font-semibold text-fd-foreground">{g.label}</div>
            <div className="flex justify-center gap-1.5">
              {g.bits.map((b, i) => (
                <div
                  key={i}
                  className="flex h-9 w-10 flex-col items-center justify-center rounded border text-[13px] font-bold"
                  style={
                    b
                      ? { background: g.soft, borderColor: g.color, color: 'var(--color-fd-foreground)' }
                      : { borderColor: 'var(--color-fd-border)', color: 'var(--color-fd-muted-foreground)' }
                  }
                >
                  <span className="font-mono">{b ? RWX[i] : '-'}</span>
                  <span className="text-[9px] text-fd-muted-foreground">{WEIGHTS[i]}</span>
                </div>
              ))}
            </div>
            <div className="mt-1 font-mono text-xl font-bold" style={{ color: g.color }}>
              {digit(g.bits)}
            </div>
          </div>
        ))}
      </div>

      <div className="mt-4 flex flex-wrap gap-4 text-sm text-fd-muted-foreground">
        <span>
          <b className="font-mono text-fd-foreground">r</b> {t.r} · 4
        </span>
        <span>
          <b className="font-mono text-fd-foreground">w</b> {t.w} · 2
        </span>
        <span>
          <b className="font-mono text-fd-foreground">x</b> {t.x} · 1
        </span>
      </div>
      <p className="mt-3 text-[13px] leading-relaxed text-fd-muted-foreground">{t.note}</p>
    </figure>
  );
}
